title: Agus S. Mubarok
author: Agus S. Mubarok
description: Personal Portfolio for Agus Syahril Mubarok A Software Engineer, Mobile Engineer. Agus Syahril Mubarok
url: https://agussmkertjhaan.github.io/
timezone: Asia/Jakarta

links:
  github: https://github.com/agussmkertjhaan
  linkedin: https://www.linkedin.com/in/agussmkertjhaan
  instagram: https://www.instagram.com/agussmkertjhaan
  twitter: https://twitter.com/agussmkertjhaan
  gdev: https://developers.google.com/profile/u/agussmkertjhaan
  email: mailto:agussmkertjhaan@gmail.com
  cekongkir: https://drive.google.com/file/d/16cKzbryjuKzbP28u8lABvvW1MFNXdGz0/view?usp=sharing
  jekyll: https://jekyllrb.com

collections:
  posts:
    output: true
    permalink: /news/:title

paginate: 8
paginate_path: /news/:num

sass:
  style: compressed
strict_front_matter: true

twitter:
  username: agussmkertjhaan
  card: summary

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-mentions
- jekyll-mermaid
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
- jekyll-redirect-from

# https://jekyllrb.com/docs/configuration/default/
exclude:
- .github
- .gitignore
- .jekyll-cache
- .sass-cache
- CNAME
- LICENSE
- README.md
